trigger:
- main

parameters:
- name: BOOKING_DATE  
  type: string
  displayName: 'Default: One week from today (YYYY-MM-DD)'
  default: $[formatDate(addDays(utcNow(), 7), 'yyyy-MM-dd')]

pool:
  vmImage: ubuntu-latest

variables:
- group: squash-court-booker-variables
- group: squash-court-booker-secrets
- name: FIRST_SLOT
  value: '18:00'
- name: SECOND_SLOT
  value: '19:00'
- name: SLOT_TIME_LIMIT
  value: '60'
- name: USERNAME_FIRST_BOOKING
  value: MarcoDeBarros1997
- name: SECOND_PLAYER_FIRST_NAME 
  value: 'Stehan'
- name: SECOND_PLAYER_LAST_NAME 
  value: 'Du Plooy'

stages:
- stage: Setup_Environment
  jobs:
  - job: Set_Environment_Variables
    steps:
    - script: |
        export USERNAME=$(echo $(USERNAME_FIRST_BOOKING))
        export PASSWORD=$(echo ${{ variables.PASSWORD }})
        export BASE_URL=$(echo ${{ variables.BASE_URL }})
        export FIRST_SLOT=$(echo $(FIRST_SLOT))
        export SLOT_TIME_LIMIT=$(echo $(SLOT_TIME_LIMIT))
        export SECOND_PLAYER_FIRST_NAME=$(echo $(SECOND_PLAYER_FIRST_NAME))
        export SECOND_PLAYER_LAST_NAME=$(echo $(SECOND_PLAYER_LAST_NAME))
        export BOOKING_DATE=$(echo ${{ variables.BOOKING_DATE }})
        cd src/
      displayName: 'Set Environment Variables'

- stage: First_Booking
  jobs:
  - job: Run_Python_Script
    steps:
    - task: PythonScript@0
      inputs:
        scriptSource: 'inline'
        script: |
          ls
          cd src/
      displayName: 'Execute Python Script'