trigger:
- main

parameters:
- name: BOOKING_DATE  
  type: string
  displayName: 'Default: One week from today (YYYY-MM-DD)'
  default: $(python -c "from datetime import datetime, timedelta; print((datetime.utcnow() + timedelta(days=7)).strftime('%Y-%m-%d'))")

pool:
  vmImage: ubuntu-latest

variables:
- group: squash_court_booker_variables
- group: squash_court_booker_secrets
- name: FIRST_SLOT
  value: 18:00
- name: SECOND_SLOT
  value: 19:00
- name: SLOT_TIME_LIMIT
  value: 60
- name: USERNAME_FIRST_BOOKING
  value: MarcoDeBarros1997
- name: SECOND_PLAYER_FIRST_NAME
  value: Stehan
- name: SECOND_PLAYER_LAST_NAME
  value: Du Plooy

stages:
- stage: Key_Vault
  jobs:
  - job: Key_Vault
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'MarcoPersonalSubscription (24fae4d7-25bc-438f-aad0-b45df9237871)'
        KeyVaultName: 'account-secrets'
        RunAsPreJob: true
    
- stage: First_Booking
  jobs:
  - job: Run_Python_Script
    steps:
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'
    - task: PythonScript@0
      inputs:
        arguments: |
          --USERNAME $(USERNAME)
          --PASSWORD $(PASSWORD)
          --BASE_URL $(BASE_URL)
          --FIRST_SLOT $(FIRST_SLOT)
          --SLOT_TIME_LIMIT $(SLOT_TIME_LIMIT)
          --SECOND_PLAYER_FIRST_NAME $(SECOND_PLAYER_FIRST_NAME)
          --SECOND_PLAYER_LAST_NAME $(SECOND_PLAYER_LAST_NAME)
          --BOOKING_DATE $(BOOKING_DATE)
        scriptSource: 'filePath'
        scriptPath: 'src/squash_court_booker.py'
      displayName: 'Execute Python Script'