# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    ls -ltra
    pip install -r requirements.txt
    cd src/
    export PYTHONPATH="$PWD:src/"
    python squash_court_booker.py
  displayName: 'Run court booking script'
