parameters:
- name: BOOKING_DATE_OVERRIDE
  type: string
  default: $[formatDate(addDays(utcNow(), 7), 'yyyy-MM-dd')]

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: squash-court-booker-variables
- group: squash-court-booker-secrets
- name: FIRST_SLOT
  value: '18:00'
- name: SECOND_SLOT
  value: '19:00'
- name: SLOT_TIME_LIMIT
  value: '60'
- name: USERNAME_FIRST_BOOKING
  value: MarcoDeBarros1997
- name: SECOND_PLAYER_FIRST_NAME 
  value: 'Stehan'
- name: SECOND_PLAYER_LAST_NAME 
  value: 'Du Plooy'
- name: BOOKING_DATE
  value: $[parameters.BOOKING_DATE_OVERRIDE] # Use custom variable if provided, otherwise use default

stages:
- stage: Setup Environment
  jobs:
  - job: Set Environment Variables
    steps:
    - script: |
        export USERNAME=$(echo $(USERNAME_FIRST_BOOKING))
        export PASSWORD=$(echo $(squash-court-booker-secrets.PASSWORD))
        export BASE_URL=$(echo $(squash-court-booker-variables.BASE_URL))
        export FIRST_SLOT=$(echo $(USERNAME_FIRST_BOOKING))
        export SLOT_TIME_LIMIT=$(echo $(USERNAME_FIRST_BOOKING))
        export SECOND_PLAYER_FIRST_NAME=$(echo $(SECOND_PLAYER_FIRST_NAME))
        export SECOND_PLAYER_LAST_NAME=$(echo $(SECOND_PLAYER_LAST_NAME))
        export BOOKING_DATE=$[variables.BOOKING_DATE]
      displayName: 'Set Environment Variables'

- stage: First Booking
  jobs:
  - job: Run Python Script
    steps:
    - task: PythonScript@0
      inputs:
        scriptSource: 'inline'
        script: |
          python src/squash_court_booker.py
      displayName: 'Execute Python Script'