trigger:
- main

parameters:
- name: BOOKING_DATE  
  type: string
  displayName: 'Default: One week from today (YYYY-MM-DD)'
  default: $[formatDate(addDays(utcNow(), 7), 'yyyy-MM-dd')]

pool:
  vmImage: ubuntu-latest

variables:
- group: squash_court_booker_variables
- group: squash_court_booker_secrets
- name: FIRST_SLOT
  value: 18:00
- name: SECOND_SLOT
  value: 19:00
- name: SLOT_TIME_LIMIT
  value: 60
- name: USERNAME_FIRST_BOOKING
  value: MarcoDeBarros1997
- name: SECOND_PLAYER_FIRST_NAME 
  value: Stehan
- name: SECOND_PLAYER_LAST_NAME 
  value: Du Plooy

stages:
- stage: Key_Vault
  jobs:
  - job: Key_Vault
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'MarcoPersonalSubscription (24fae4d7-25bc-438f-aad0-b45df9237871)'
        KeyVaultName: 'account-secrets'
        RunAsPreJob: true
    
- stage: First_Booking
  jobs:
  - job: Run_Python_Script
    steps:
    - script: |
        set -x
        export USERNAME=$(echo $(USERNAME_FIRST_BOOKING))
        export PASSWORD=$(echo $(KampongPasswordMarco))
        export BASE_URL=$(echo $(BASE_URL))
        export FIRST_SLOT=$(echo $(FIRST_SLOT))
        export SLOT_TIME_LIMIT=$(echo $(SLOT_TIME_LIMIT))
        export SECOND_PLAYER_FIRST_NAME=$(echo $(SECOND_PLAYER_FIRST_NAME))
        export SECOND_PLAYER_LAST_NAME=$(echo $(SECOND_PLAYER_LAST_NAME))
        export BOOKING_DATE=$(echo ${{ parameters.BOOKING_DATE }})
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'
    - task: PythonScript@0
      inputs:
        scriptSource: 'filePath'
        scriptPath: 'src/squash_court_booker.py'
      displayName: 'Execute Python Script'